server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  datasource:
      # 当前数据源操作类型
      type: com.alibaba.druid.pool.DruidDataSource
      # mysql驱动类
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: yue170305
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

