server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
        routes:
          - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
            #匹配后提供服务的路由地址
            #uri: http://localhost:8001
            uri: lb://paymentService
            predicates:
              - Path=/cloud2020/payment/findById/** # 断言，路径相匹配的进行路由

          - id: payment_route2
            #uri: http://localhost:8001
            uri: lb://paymentService
            predicates:
            - Path=/cloud2020/payment/create/** #断言,路径相匹配的进行路由
            - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
            #- Cookie=username,eiletxie   #带Cookie，并且username的值为eiletxie
            #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka/
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/